# Generated by Django 3.0.8 on 2020-07-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorinfo',
            old_name='fName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='authorinfo',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='authorinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authorinfo',
            name='lName',
        ),
    ]
